// Generated by gencpp from file laikago_msgs/LowState.msg
// DO NOT EDIT!


#ifndef LAIKAGO_MSGS_MESSAGE_LOWSTATE_H
#define LAIKAGO_MSGS_MESSAGE_LOWSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <laikago_msgs/IMU.h>
#include <laikago_msgs/MotorState.h>
#include <laikago_msgs/Cartesian.h>

namespace laikago_msgs
{
template <class ContainerAllocator>
struct LowState_
{
  typedef LowState_<ContainerAllocator> Type;

  LowState_()
    : levelFlag(0)
    , imu()
    , motorState()
    , footForce()
    , tick(0)
    , wirelessRemote()
    , crc(0)
    , eeForce()  {
      footForce.assign(0.0);

      wirelessRemote.assign(0);
  }
  LowState_(const ContainerAllocator& _alloc)
    : levelFlag(0)
    , imu(_alloc)
    , motorState()
    , footForce()
    , tick(0)
    , wirelessRemote()
    , crc(0)
    , eeForce()  {
  (void)_alloc;
      motorState.assign( ::laikago_msgs::MotorState_<ContainerAllocator> (_alloc));

      footForce.assign(0.0);

      wirelessRemote.assign(0);

      eeForce.assign( ::laikago_msgs::Cartesian_<ContainerAllocator> (_alloc));
  }



   typedef uint8_t _levelFlag_type;
  _levelFlag_type levelFlag;

   typedef  ::laikago_msgs::IMU_<ContainerAllocator>  _imu_type;
  _imu_type imu;

   typedef boost::array< ::laikago_msgs::MotorState_<ContainerAllocator> , 20>  _motorState_type;
  _motorState_type motorState;

   typedef boost::array<float, 4>  _footForce_type;
  _footForce_type footForce;

   typedef uint32_t _tick_type;
  _tick_type tick;

   typedef boost::array<uint8_t, 40>  _wirelessRemote_type;
  _wirelessRemote_type wirelessRemote;

   typedef uint32_t _crc_type;
  _crc_type crc;

   typedef boost::array< ::laikago_msgs::Cartesian_<ContainerAllocator> , 4>  _eeForce_type;
  _eeForce_type eeForce;





  typedef boost::shared_ptr< ::laikago_msgs::LowState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laikago_msgs::LowState_<ContainerAllocator> const> ConstPtr;

}; // struct LowState_

typedef ::laikago_msgs::LowState_<std::allocator<void> > LowState;

typedef boost::shared_ptr< ::laikago_msgs::LowState > LowStatePtr;
typedef boost::shared_ptr< ::laikago_msgs::LowState const> LowStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laikago_msgs::LowState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laikago_msgs::LowState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laikago_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'laikago_msgs': ['/home/unitree/catkin_ws/src/laikago_ros/laikago_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laikago_msgs::LowState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laikago_msgs::LowState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laikago_msgs::LowState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laikago_msgs::LowState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laikago_msgs::LowState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laikago_msgs::LowState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laikago_msgs::LowState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff497aa2c0f42e68227aaf7b1f8c13c1";
  }

  static const char* value(const ::laikago_msgs::LowState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff497aa2c0f42e68ULL;
  static const uint64_t static_value2 = 0x227aaf7b1f8c13c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::laikago_msgs::LowState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laikago_msgs/LowState";
  }

  static const char* value(const ::laikago_msgs::LowState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laikago_msgs::LowState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 levelFlag\n\
IMU imu\n\
MotorState[20] motorState\n\
float32[4] footForce\n\
uint32 tick                   # time reference\n\
uint8[40] wirelessRemote      # wireless command\n\
uint32 crc                    # check bit\n\
Cartesian[4] eeForce          #it's a 1-DOF force infact, but we use 3-DOF here just for visualization \n\
================================================================================\n\
MSG: laikago_msgs/IMU\n\
float32[4] quaternion\n\
float32[3] gyroscope\n\
float32[3] acceleration\n\
float32[3] rpy\n\
float32 temp\n\
================================================================================\n\
MSG: laikago_msgs/MotorState\n\
uint8 mode            # motor current mode \n\
float32 position     # motor current position（rad）\n\
float32 velocity     # motor current speed（rad/s）\n\
float32 torque       # current estimated output torque（N*m）\n\
float32 temperature  # motor temperature（slow conduction of temperature leads to lag）\n\
int32 iReserve\n\
float32 fReserve\n\
================================================================================\n\
MSG: laikago_msgs/Cartesian\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::laikago_msgs::LowState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laikago_msgs::LowState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.levelFlag);
      stream.next(m.imu);
      stream.next(m.motorState);
      stream.next(m.footForce);
      stream.next(m.tick);
      stream.next(m.wirelessRemote);
      stream.next(m.crc);
      stream.next(m.eeForce);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LowState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laikago_msgs::LowState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laikago_msgs::LowState_<ContainerAllocator>& v)
  {
    s << indent << "levelFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.levelFlag);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::laikago_msgs::IMU_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "motorState[]" << std::endl;
    for (size_t i = 0; i < v.motorState.size(); ++i)
    {
      s << indent << "  motorState[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laikago_msgs::MotorState_<ContainerAllocator> >::stream(s, indent + "    ", v.motorState[i]);
    }
    s << indent << "footForce[]" << std::endl;
    for (size_t i = 0; i < v.footForce.size(); ++i)
    {
      s << indent << "  footForce[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.footForce[i]);
    }
    s << indent << "tick: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tick);
    s << indent << "wirelessRemote[]" << std::endl;
    for (size_t i = 0; i < v.wirelessRemote.size(); ++i)
    {
      s << indent << "  wirelessRemote[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.wirelessRemote[i]);
    }
    s << indent << "crc: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.crc);
    s << indent << "eeForce[]" << std::endl;
    for (size_t i = 0; i < v.eeForce.size(); ++i)
    {
      s << indent << "  eeForce[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laikago_msgs::Cartesian_<ContainerAllocator> >::stream(s, indent + "    ", v.eeForce[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAIKAGO_MSGS_MESSAGE_LOWSTATE_H
