# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from laikago_msgs/HighState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import laikago_msgs.msg

class HighState(genpy.Message):
  _md5sum = "01d4600477cd3acd91bd469708ab5526"
  _type = "laikago_msgs/HighState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 levelFlag
uint8 mode
IMU imu
float32 forwardSpeed
float32 sideSpeed
float32 rotateSpeed
float32 bodyHeight
float32 updownSpeed
Cartesian forwardPosition       # (will be float type next version)
Cartesian sidePosition          # (will be float type next version)
Cartesian[4] footPosition2Body
Cartesian[4] footSpeed2Body
float32[4] footForce    
uint32 tick               
uint8[40] wirelessRemote
uint32 crc

# Under are not defined in SDK yet.
Cartesian[4] eeForce            # It's a 1-DOF force in real robot, but 3-DOF is better for visualization.
float32[12] jointP              # for visualization

================================================================================
MSG: laikago_msgs/IMU
float32[4] quaternion
float32[3] gyroscope
float32[3] acceleration
float32[3] rpy
float32 temp
================================================================================
MSG: laikago_msgs/Cartesian
float32 x
float32 y
float32 z"""
  __slots__ = ['levelFlag','mode','imu','forwardSpeed','sideSpeed','rotateSpeed','bodyHeight','updownSpeed','forwardPosition','sidePosition','footPosition2Body','footSpeed2Body','footForce','tick','wirelessRemote','crc','eeForce','jointP']
  _slot_types = ['uint8','uint8','laikago_msgs/IMU','float32','float32','float32','float32','float32','laikago_msgs/Cartesian','laikago_msgs/Cartesian','laikago_msgs/Cartesian[4]','laikago_msgs/Cartesian[4]','float32[4]','uint32','uint8[40]','uint32','laikago_msgs/Cartesian[4]','float32[12]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       levelFlag,mode,imu,forwardSpeed,sideSpeed,rotateSpeed,bodyHeight,updownSpeed,forwardPosition,sidePosition,footPosition2Body,footSpeed2Body,footForce,tick,wirelessRemote,crc,eeForce,jointP

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HighState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.levelFlag is None:
        self.levelFlag = 0
      if self.mode is None:
        self.mode = 0
      if self.imu is None:
        self.imu = laikago_msgs.msg.IMU()
      if self.forwardSpeed is None:
        self.forwardSpeed = 0.
      if self.sideSpeed is None:
        self.sideSpeed = 0.
      if self.rotateSpeed is None:
        self.rotateSpeed = 0.
      if self.bodyHeight is None:
        self.bodyHeight = 0.
      if self.updownSpeed is None:
        self.updownSpeed = 0.
      if self.forwardPosition is None:
        self.forwardPosition = laikago_msgs.msg.Cartesian()
      if self.sidePosition is None:
        self.sidePosition = laikago_msgs.msg.Cartesian()
      if self.footPosition2Body is None:
        self.footPosition2Body = [laikago_msgs.msg.Cartesian() for _ in range(4)]
      if self.footSpeed2Body is None:
        self.footSpeed2Body = [laikago_msgs.msg.Cartesian() for _ in range(4)]
      if self.footForce is None:
        self.footForce = [0.] * 4
      if self.tick is None:
        self.tick = 0
      if self.wirelessRemote is None:
        self.wirelessRemote = b'\0'*40
      if self.crc is None:
        self.crc = 0
      if self.eeForce is None:
        self.eeForce = [laikago_msgs.msg.Cartesian() for _ in range(4)]
      if self.jointP is None:
        self.jointP = [0.] * 12
    else:
      self.levelFlag = 0
      self.mode = 0
      self.imu = laikago_msgs.msg.IMU()
      self.forwardSpeed = 0.
      self.sideSpeed = 0.
      self.rotateSpeed = 0.
      self.bodyHeight = 0.
      self.updownSpeed = 0.
      self.forwardPosition = laikago_msgs.msg.Cartesian()
      self.sidePosition = laikago_msgs.msg.Cartesian()
      self.footPosition2Body = [laikago_msgs.msg.Cartesian() for _ in range(4)]
      self.footSpeed2Body = [laikago_msgs.msg.Cartesian() for _ in range(4)]
      self.footForce = [0.] * 4
      self.tick = 0
      self.wirelessRemote = b'\0'*40
      self.crc = 0
      self.eeForce = [laikago_msgs.msg.Cartesian() for _ in range(4)]
      self.jointP = [0.] * 12

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.levelFlag, _x.mode))
      buff.write(_get_struct_4f().pack(*self.imu.quaternion))
      buff.write(_get_struct_3f().pack(*self.imu.gyroscope))
      buff.write(_get_struct_3f().pack(*self.imu.acceleration))
      buff.write(_get_struct_3f().pack(*self.imu.rpy))
      _x = self
      buff.write(_get_struct_12f().pack(_x.imu.temp, _x.forwardSpeed, _x.sideSpeed, _x.rotateSpeed, _x.bodyHeight, _x.updownSpeed, _x.forwardPosition.x, _x.forwardPosition.y, _x.forwardPosition.z, _x.sidePosition.x, _x.sidePosition.y, _x.sidePosition.z))
      for val1 in self.footPosition2Body:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      for val1 in self.footSpeed2Body:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      buff.write(_get_struct_4f().pack(*self.footForce))
      buff.write(_get_struct_I().pack(self.tick))
      _x = self.wirelessRemote
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_40B().pack(*_x))
      else:
        buff.write(_get_struct_40s().pack(_x))
      buff.write(_get_struct_I().pack(self.crc))
      for val1 in self.eeForce:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      buff.write(_get_struct_12f().pack(*self.jointP))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.imu is None:
        self.imu = laikago_msgs.msg.IMU()
      if self.forwardPosition is None:
        self.forwardPosition = laikago_msgs.msg.Cartesian()
      if self.sidePosition is None:
        self.sidePosition = laikago_msgs.msg.Cartesian()
      if self.footPosition2Body is None:
        self.footPosition2Body = None
      if self.footSpeed2Body is None:
        self.footSpeed2Body = None
      if self.eeForce is None:
        self.eeForce = None
      end = 0
      _x = self
      start = end
      end += 2
      (_x.levelFlag, _x.mode,) = _get_struct_2B().unpack(str[start:end])
      start = end
      end += 16
      self.imu.quaternion = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 12
      self.imu.gyroscope = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.imu.acceleration = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.imu.rpy = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.imu.temp, _x.forwardSpeed, _x.sideSpeed, _x.rotateSpeed, _x.bodyHeight, _x.updownSpeed, _x.forwardPosition.x, _x.forwardPosition.y, _x.forwardPosition.z, _x.sidePosition.x, _x.sidePosition.y, _x.sidePosition.z,) = _get_struct_12f().unpack(str[start:end])
      self.footPosition2Body = []
      for i in range(0, 4):
        val1 = laikago_msgs.msg.Cartesian()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.footPosition2Body.append(val1)
      self.footSpeed2Body = []
      for i in range(0, 4):
        val1 = laikago_msgs.msg.Cartesian()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.footSpeed2Body.append(val1)
      start = end
      end += 16
      self.footForce = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 4
      (self.tick,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 40
      self.wirelessRemote = str[start:end]
      start = end
      end += 4
      (self.crc,) = _get_struct_I().unpack(str[start:end])
      self.eeForce = []
      for i in range(0, 4):
        val1 = laikago_msgs.msg.Cartesian()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.eeForce.append(val1)
      start = end
      end += 48
      self.jointP = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.levelFlag, _x.mode))
      buff.write(self.imu.quaternion.tostring())
      buff.write(self.imu.gyroscope.tostring())
      buff.write(self.imu.acceleration.tostring())
      buff.write(self.imu.rpy.tostring())
      _x = self
      buff.write(_get_struct_12f().pack(_x.imu.temp, _x.forwardSpeed, _x.sideSpeed, _x.rotateSpeed, _x.bodyHeight, _x.updownSpeed, _x.forwardPosition.x, _x.forwardPosition.y, _x.forwardPosition.z, _x.sidePosition.x, _x.sidePosition.y, _x.sidePosition.z))
      for val1 in self.footPosition2Body:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      for val1 in self.footSpeed2Body:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      buff.write(self.footForce.tostring())
      buff.write(_get_struct_I().pack(self.tick))
      _x = self.wirelessRemote
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_40B().pack(*_x))
      else:
        buff.write(_get_struct_40s().pack(_x))
      buff.write(_get_struct_I().pack(self.crc))
      for val1 in self.eeForce:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      buff.write(self.jointP.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.imu is None:
        self.imu = laikago_msgs.msg.IMU()
      if self.forwardPosition is None:
        self.forwardPosition = laikago_msgs.msg.Cartesian()
      if self.sidePosition is None:
        self.sidePosition = laikago_msgs.msg.Cartesian()
      if self.footPosition2Body is None:
        self.footPosition2Body = None
      if self.footSpeed2Body is None:
        self.footSpeed2Body = None
      if self.eeForce is None:
        self.eeForce = None
      end = 0
      _x = self
      start = end
      end += 2
      (_x.levelFlag, _x.mode,) = _get_struct_2B().unpack(str[start:end])
      start = end
      end += 16
      self.imu.quaternion = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      start = end
      end += 12
      self.imu.gyroscope = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.imu.acceleration = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.imu.rpy = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 48
      (_x.imu.temp, _x.forwardSpeed, _x.sideSpeed, _x.rotateSpeed, _x.bodyHeight, _x.updownSpeed, _x.forwardPosition.x, _x.forwardPosition.y, _x.forwardPosition.z, _x.sidePosition.x, _x.sidePosition.y, _x.sidePosition.z,) = _get_struct_12f().unpack(str[start:end])
      self.footPosition2Body = []
      for i in range(0, 4):
        val1 = laikago_msgs.msg.Cartesian()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.footPosition2Body.append(val1)
      self.footSpeed2Body = []
      for i in range(0, 4):
        val1 = laikago_msgs.msg.Cartesian()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.footSpeed2Body.append(val1)
      start = end
      end += 16
      self.footForce = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      start = end
      end += 4
      (self.tick,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 40
      self.wirelessRemote = str[start:end]
      start = end
      end += 4
      (self.crc,) = _get_struct_I().unpack(str[start:end])
      self.eeForce = []
      for i in range(0, 4):
        val1 = laikago_msgs.msg.Cartesian()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.eeForce.append(val1)
      start = end
      end += 48
      self.jointP = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=12)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_40B = None
def _get_struct_40B():
    global _struct_40B
    if _struct_40B is None:
        _struct_40B = struct.Struct("<40B")
    return _struct_40B
_struct_12f = None
def _get_struct_12f():
    global _struct_12f
    if _struct_12f is None:
        _struct_12f = struct.Struct("<12f")
    return _struct_12f
_struct_40s = None
def _get_struct_40s():
    global _struct_40s
    if _struct_40s is None:
        _struct_40s = struct.Struct("<40s")
    return _struct_40s
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
