# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from laikago_msgs/MotorState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorState(genpy.Message):
  _md5sum = "45138c3d7a603ce307daeb241ea2207a"
  _type = "laikago_msgs/MotorState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 mode            # motor current mode 
float32 position     # motor current position（rad）
float32 velocity     # motor current speed（rad/s）
float32 torque       # current estimated output torque（N*m）
float32 temperature  # motor temperature（slow conduction of temperature leads to lag）
int32 iReserve
float32 fReserve"""
  __slots__ = ['mode','position','velocity','torque','temperature','iReserve','fReserve']
  _slot_types = ['uint8','float32','float32','float32','float32','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,position,velocity,torque,temperature,iReserve,fReserve

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = 0
      if self.position is None:
        self.position = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.torque is None:
        self.torque = 0.
      if self.temperature is None:
        self.temperature = 0.
      if self.iReserve is None:
        self.iReserve = 0
      if self.fReserve is None:
        self.fReserve = 0.
    else:
      self.mode = 0
      self.position = 0.
      self.velocity = 0.
      self.torque = 0.
      self.temperature = 0.
      self.iReserve = 0
      self.fReserve = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4fif().pack(_x.mode, _x.position, _x.velocity, _x.torque, _x.temperature, _x.iReserve, _x.fReserve))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.mode, _x.position, _x.velocity, _x.torque, _x.temperature, _x.iReserve, _x.fReserve,) = _get_struct_B4fif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4fif().pack(_x.mode, _x.position, _x.velocity, _x.torque, _x.temperature, _x.iReserve, _x.fReserve))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.mode, _x.position, _x.velocity, _x.torque, _x.temperature, _x.iReserve, _x.fReserve,) = _get_struct_B4fif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4fif = None
def _get_struct_B4fif():
    global _struct_B4fif
    if _struct_B4fif is None:
        _struct_B4fif = struct.Struct("<B4fif")
    return _struct_B4fif
