(cl:in-package laikago_msgs-msg)
(cl:export '(LEVELFLAG-VAL
          LEVELFLAG
          MODE-VAL
          MODE
          IMU-VAL
          IMU
          FORWARDSPEED-VAL
          FORWARDSPEED
          SIDESPEED-VAL
          SIDESPEED
          ROTATESPEED-VAL
          ROTATESPEED
          BODYHEIGHT-VAL
          BODYHEIGHT
          UPDOWNSPEED-VAL
          UPDOWNSPEED
          FORWARDPOSITION-VAL
          FORWARDPOSITION
          SIDEPOSITION-VAL
          SIDEPOSITION
          FOOTPOSITION2BODY-VAL
          FOOTPOSITION2BODY
          FOOTSPEED2BODY-VAL
          FOOTSPEED2BODY
          FOOTFORCE-VAL
          FOOTFORCE
          TICK-VAL
          TICK
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          CRC-VAL
          CRC
          EEFORCE-VAL
          EEFORCE
          JOINTP-VAL
          JOINTP
))